(defsystem #:cl-codegraph-tests
  :depends-on (#:cl-codegraph #:fiveam)
  :serial t
  :components ((:module "tests"
                :components ((:file "package")
                             (:file "suite-core")
                             (:file "suite-calls")
                             (:file "suite-cross-package")
                             (:file "suite-metadata")
                             (:file "suite-macro-var-deps")
                             (:file "suite-query-helpers")
                             (:file "suite-internal")
                             (:file "suite-visualization")
                             (:file "suite-diff")
                             (:file "suite-multi-package")
                             (:file "suite-advanced-queries")
                             (:file "suite-incremental")
                             (:file "suite-repl")
                             (:file "suite-unused-imports")
                             (:file "suite-monitor")
                             (:file "suite-monitor-vars")
                             (:file "suite-auto-monitor")
                             (:file "suite-var-value")
                             (:file "suite-per-method-calls")
                             (:file "suite-local-context")
                             (:file "suite-accessors")))))
